config/routes.rb
Rails.application.routes.draw do
  root "events#index"

  devise_for :users, :controllers => { registrations: 'registrations' }

  devise_scope :user do
    get 'sign_out', to: 'devise/sessions#destroy', as: 'sign_out_path'
    get 'sign_in', to: 'devise/sessions#new', as: 'sign_in_path'
  end

  resources :events do
    member do
      get 'attend'
      get 'unattend'
    end
  end
  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  validates :title, :datetime, presence: true

  belongs_to :creator, class_name: 'User'
  has_many :event_attendances, foreign_key: :attended_event_id
  has_many :attendees, through: :event_attendances, source: :attendee

  scope :past, -> { where('datetime < ?', Time.now).order(datetime: :desc) }
  scope :upcoming, -> { where('datetime > ?', Time.now).order(datetime: :asc) }
end

app/models/event_attendance.rb
class EventAttendance < ApplicationRecord
  belongs_to :attendee, class_name: 'User'
  belongs_to :attended_event, class_name: 'Event'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :created_events, foreign_key: 'creator_id', class_name: 'Event'
  has_many :event_attendances, foreign_key: :attendee_id
  has_many :attended_events, through: :event_attendances, source: :attended_event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def create
    @user = current_user
    @event = @user.created_events.build(event_params)

    if @event.save
      redirect_to @event, notice: 'Your event was created'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      redirect_to @event, notice: 'Your event was updated'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_path
  end

  def attend
    @user = current_user
    @event = Event.find(params[:id])

    if @event.attendees.include?(@user)
      redirect_to @event, notice: "You are already attending this event"
    else
      @event.attendees << @user
      redirect_to @event
    end
  end

  def unattend
    @user = current_user
    @event = Event.find(params[:id])

    @event.attendees.delete(@user)
    redirect_to @event, notice: "You are no longer attending this event"
  end

  private

  def event_params
    params.require(:event).permit(:title, :datetime, :location)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:email, :password, :name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_with model: event do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div>
    <%= form.label :datetime %>
    <%= form.datetime_field :datetime %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/events/_nav.html.erb
<% if user_signed_in? %>
  <nav>
    <%= link_to 'Home', events_path %> |
    <%= link_to 'Profile', user_path(current_user) %> |
    <%= link_to 'New Event', new_event_path %> |
    <%= link_to 'Sign Out', sign_out_path_url, method: :delete %>
  </nav>
<% else %>
  <nav>
    <%= link_to 'Home', events_path %> |
    <%= link_to 'Sign In', sign_in_path_url%>
  </nav>
<% end %>

app/views/events/edit.html.erb
<%= render 'nav' %>

<h1>Edit Event</h1>

<%= render 'form', event: @event %>

app/views/events/index.html.erb
<%= render 'nav' %>
<% if user_signed_in? %>
  <h1>Hello, <%= current_user.name %>!</h1>
<% else %>
  <h1>Welcome!</h1>
<% end %>
<h3>Upcoming Events</h3>
<ul>
  <% @events.upcoming.each do |event| %>
    <li>
      <%= link_to event.title, event %> — <%= event.datetime.strftime('%a, %b %e @ %l:%M %p') %>
      <div>created by <%= event.creator.name %></div><br />
    </li>
  <% end %>
</ul>

<h3>Past Events</h3>
<ul>
  <% @events.past.each do |event| %>
    <li>
      <%= link_to event.title, event %> — <%= event.datetime.strftime('%a, %b %e @ %l:%M %p') %>
      <div>created by <%= event.creator.name %></div><br />
    </li>
  <% end %>
</ul>

app/views/events/new.html.erb
<%= render 'nav' %>

<h1>New Event</h1>

<%= render 'form', event: @event %>

app/views/events/show.html.erb
<%= render 'nav' %>

<h1><%= @event.title %></h1>

<p><strong>Event Creator:</strong> <%= link_to @event.creator.name, user_path(@event.creator) %> (<%= link_to @event.creator.email, 'mailto:#{@event.creator.email}' %>)</p>

<p><strong>Event Date:</strong> <%= @event.datetime.strftime('%A, %B %e, %Y at %l:%M %p') %></p>

<p><strong>Event Location:</strong> <%= @event.location %></p>

<p><strong>Event Attendees:</strong></p>
<ul>
<% @event.attendees.each do |attendee| %>
  <% unless attendee == current_user %>
    <li>
      <%= attendee.name %>
    </li>
  <% end %>
<% end %>
</ul>

<% if current_user == @event.creator %>
  <%= link_to 'Edit', edit_event_path %> |
  <%= link_to 'Delete', event_path(@event), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this event?" } %>
<% elsif @event.attendees.include?(current_user) %>
  <%= link_to 'Cancel RSVP', unattend_event_path unless @event.datetime < Time.now %>
  <p>You're attending this event.</p>
<% else %>
  <%= link_to 'RSVP', attend_event_path unless @event.datetime < Time.now %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<%= render :partial => '/events/nav' %>

<% @user = User.find(params[:id])%>
<% if @user == current_user %>
  <h1>My Events</h1>
  <ul>
    <% @user.created_events.sort_by(&:datetime).each do |event| %>
      <li>
        <%= link_to event.title, event %>
      </li>
    <% end %>
  </ul>

  <h2>Events I'm Attending</h2>
  <h3>Upcoming Events</h3>
  <ul>
    <% @user.attended_events.sort_by(&:datetime).select { |event| event.datetime > Time.now }.each do |event| %>
      <li>
        <%= link_to event.title, event %>
      </li>
    <% end %>
  </ul>

  <h3>Past Events</h3>
  <ul>
    <% @user.attended_events.sort_by(&:datetime).select { |event| event.datetime < Time.now }.each do |event| %>
      <li>
        <%= link_to event.title, event %>
      </li>
    <% end %>
  </ul>

<% else %>
  <h1><%= @user.name.possessive %> Events</h1>
  <ul>
    <% @user.created_events.sort_by(&:datetime).each do |event| %>
      <li>
        <%= link_to event.title, event %>
      </li>
    <% end %>
  </ul>

  <h2>Events <%= @user.name %> is Attending</h2>

  <h3>Upcoming Events</h3>
  <ul>
    <% @user.attended_events.sort_by(&:datetime).select { |event| event.datetime > Time.now }.each do |event| %>
      <li>
        <%= link_to event.title, event %>
      </li>
    <% end %>
  </ul>

  <h3>Past Events</h3>
  <ul>
    <% @user.attended_events.sort_by(&:datetime).select { |event| event.datetime < Time.now }.each do |event| %>
      <li>
        <%= link_to event.title, event %>
      </li>
    <% end %>
  </ul>
<% end %>